spring:
  rabbitmq:
    host: localhost
    port: 5672
    virtual-host: /nflj
    username: admin
    password: admin
    publisher-returns: true #消息发送到队列确认
    publisher-confirm-type: correlated #开启 confirm 确认机制,确认消息发送到交换机(Exchange),是否确定回调
  listener:
    direct: # 路由模式
      acknowledge-mode: manual # 人为地获取到channel之后调用方法向server发送ack（或消费失败时的nack）信息
      prefetch: 100 # 指定一个消费者一次可以从Rabbit中获取多少条消息并缓存在client中,一旦达到改值，Rabbit将会停止投递新的message到该consumer中直到它发出ack